"""first migrate db

Revision ID: 75836b4427f1
Revises: 
Create Date: 2020-03-21 14:52:04.756021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75836b4427f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('student')
    op.drop_table('user1')
    op.drop_column('information', 'college')
    op.drop_column('information', 'stuid')
    op.drop_column('information', 'stutype')
    op.drop_column('information', 'time')
    op.drop_column('information', 'phonenum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('phonenum', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('information', sa.Column('time', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('information', sa.Column('stutype', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('information', sa.Column('stuid', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('information', sa.Column('college', mysql.VARCHAR(length=45), nullable=True))
    op.create_table('user1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
